<a href="https://colab.research.google.com/github/FJR139/Digital-Skola-Learning/blob/main/Fajar_Kurnia_Homework_15_%E2%80%93_Exploring_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jawaban

## Nomor 1

In [ ]:
import pandas as pd
df = pd.read_excel('Homework-DataFrame-Dataset.xlsx')
df_p = pd.read_excel('Homework-DataFrame-Dataset.xlsx', sheet_name='Paid-Transaction')
df_s = pd.read_excel('Homework-DataFrame-Dataset.xlsx', sheet_name='Seller')
df.head(10)

,Paid Date,Order Number,First Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
0,20170724,201707240088517,elvride,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0
1,20170701,201707018889790,BASIR,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0
2,20170707,201707079264675,Citra,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0
3,20170720,201707209945714,Dian,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0
4,20170722,201707220002354,rizal,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0
5,20170714,201707149671962,fauzannor,andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,10400.0,9000,0.0
6,20170703,201707039018928,della,Suryo,Service/ Mokado,Pulsa Indosat REG 50.000,90000,48100,2900.0,0,0.0
7,20170707,201707079291011,Sri,Oki,Service/ Mokado,Pulsa Indosat REG 50.000,180000,96200,5800.0,0,0.0
8,20170703,201706218386960,Irene,Hana,Service/ Mokado,[BUKBER HEMAT] Es Teler 77 : Es Teler,300000,156400,10000.0,9000,0.0
9,20170724,201707230047939,tofani,Valentina,Fashion,Sandal Pria Sandal Gunung New Era CSA | 4 Model,675000,351900,22500.0,10000,0.0

In [ ]:
full_name = (df_p['First Name'] + ' ' + df_p['Last Name']).str.title()
idx = df_p.columns.get_loc('First Name')
df_p.insert(idx + 1, 'Full Name', full_name)
df_p.head(10)

,Paid Date,Order Number,First Name,Full Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,Sales Discount,Delivery Fee,Other Discount
0,20170724,201707240088517,elvride,Elvride Aries,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,10200.0,9000,0.0
1,20170701,201707018889790,BASIR,Basir Ninuk,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,0.0,0,0.0
2,20170707,201707079264675,Citra,Citra Ardi,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,700.0,0,0.0
3,20170720,201707209945714,Dian,Dian Renaldi,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,5900.0,0,0.0
4,20170722,201707220002354,rizal,Rizal Tamba,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,5600.0,0,0.0
5,20170714,201707149671962,fauzannor,Fauzannor Andri,andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,10400.0,9000,0.0
6,20170703,201707039018928,della,Della Suryo,Suryo,Service/ Mokado,Pulsa Indosat REG 50.000,90000,48100,2900.0,0,0.0
7,20170707,201707079291011,Sri,Sri Oki,Oki,Service/ Mokado,Pulsa Indosat REG 50.000,180000,96200,5800.0,0,0.0
8,20170703,201706218386960,Irene,Irene Hana,Hana,Service/ Mokado,[BUKBER HEMAT] Es Teler 77 : Es Teler,300000,156400,10000.0,9000,0.0
9,20170724,201707230047939,tofani,Tofani Valentina,Valentina,Fashion,Sandal Pria Sandal Gunung New Era CSA | 4 Model,675000,351900,22500.0,10000,0.0

## nomor 2

In [ ]:
gmv = (df_p['Transaction Amount'] - df_p['Seller Discount']) + df_p['Delivery Fee']

In [ ]:
disc_idx = df_p.columns.get_loc('Seller Discount')
df_p.insert(disc_idx + 1, 'GMV', gmv)
df_p.head(10)

,Paid Date,Order Number,First Name,Full Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount
0,20170724,201707240088517,elvride,Elvride Aries,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,156000,10200.0,9000,0.0
1,20170701,201707018889790,BASIR,Basir Ninuk,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0
2,20170707,201707079264675,Citra,Citra Ardi,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0
3,20170720,201707209945714,Dian,Dian Renaldi,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0
4,20170722,201707220002354,rizal,Rizal Tamba,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0
5,20170714,201707149671962,fauzannor,Fauzannor Andri,andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,158000,10400.0,9000,0.0
6,20170703,201707039018928,della,Della Suryo,Suryo,Service/ Mokado,Pulsa Indosat REG 50.000,90000,48100,41900,2900.0,0,0.0
7,20170707,201707079291011,Sri,Sri Oki,Oki,Service/ Mokado,Pulsa Indosat REG 50.000,180000,96200,83800,5800.0,0,0.0
8,20170703,201706218386960,Irene,Irene Hana,Hana,Service/ Mokado,[BUKBER HEMAT] Es Teler 77 : Es Teler,300000,156400,152600,10000.0,9000,0.0
9,20170724,201707230047939,tofani,Tofani Valentina,Valentina,Fashion,Sandal Pria Sandal Gunung New Era CSA | 4 Model,675000,351900,333100,22500.0,10000,0.0

## nomor 3

In [ ]:
data_group = {
    'Home/ Food': 'Group 1',
    'Sports/ Hobi/ Otomotif': 'Group 1',
    'Fashion': 'Group 1',
    'Beauty/ Health': 'Group 1',
    'Gadget/ Komputer': 'Group 2',
    'Elektronik': 'Group 2',
    'Service/ Mokado': 'Group 2',
    'Babies/ Kids': 'Group 2'
}

df_p['group'] = df_p['Meta Category'].map(data_group)
df_p.head(10)

,Paid Date,Order Number,First Name,Full Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,group
0,20170724,201707240088517,elvride,Elvride Aries,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,156000,10200.0,9000,0.0,Group 2
1,20170701,201707018889790,BASIR,Basir Ninuk,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0,Group 2
2,20170707,201707079264675,Citra,Citra Ardi,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0,Group 2
3,20170720,201707209945714,Dian,Dian Renaldi,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0,Group 1
4,20170722,201707220002354,rizal,Rizal Tamba,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0,Group 2
5,20170714,201707149671962,fauzannor,Fauzannor Andri,andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,158000,10400.0,9000,0.0,Group 2
6,20170703,201707039018928,della,Della Suryo,Suryo,Service/ Mokado,Pulsa Indosat REG 50.000,90000,48100,41900,2900.0,0,0.0,Group 2
7,20170707,201707079291011,Sri,Sri Oki,Oki,Service/ Mokado,Pulsa Indosat REG 50.000,180000,96200,83800,5800.0,0,0.0,Group 2
8,20170703,201706218386960,Irene,Irene Hana,Hana,Service/ Mokado,[BUKBER HEMAT] Es Teler 77 : Es Teler,300000,156400,152600,10000.0,9000,0.0,Group 2
9,20170724,201707230047939,tofani,Tofani Valentina,Valentina,Fashion,Sandal Pria Sandal Gunung New Era CSA | 4 Model,675000,351900,333100,22500.0,10000,0.0,Group 1

In [ ]:
df_p['Paid Date'] = pd.to_datetime(df_p['Paid Date'], format='%Y%m%d')
df_p['month'] = df_p['Paid Date'].dt.to_period('M')
df_p.head(10)

,Paid Date,Order Number,First Name,Full Name,Last Name,Meta Category,Product Name,Transaction Amount,Seller Discount,GMV,Sales Discount,Delivery Fee,Other Discount,group,month
0,2017-07-24,201707240088517,elvride,Elvride Aries,aries,Babies/ Kids,Pineapple Hat Anak Ala Korea - 6M - 4Y - Unise...,300000,153000,156000,10200.0,9000,0.0,Group 2,2017-07
1,2017-07-01,201707018889790,BASIR,Basir Ninuk,Ninuk,Service/ Mokado,Pulsa BOLT 150.000,287800,68000,219800,0.0,0,0.0,Group 2,2017-07
2,2017-07-07,201707079264675,Citra,Citra Ardi,Ardi,Service/ Mokado,"XTRA Combo 12X 6GB, 12bln",35000,0,35000,700.0,0,0.0,Group 2,2017-07
3,2017-07-20,201707209945714,Dian,Dian Renaldi,Renaldi,Fashion,Square Foldable Travel Bag / Tas Koper Luggage...,85000,0,85000,5900.0,0,0.0,Group 1,2017-07
4,2017-07-22,201707220002354,rizal,Rizal Tamba,Tamba,Gadget/ Komputer,Samsung Galaxy Note 5 Gold,81000,0,81000,5600.0,0,0.0,Group 2,2017-07
5,2017-07-14,201707149671962,fauzannor,Fauzannor Andri,andri,Service/ Mokado,Pulsa Indosat REG 50.000,149000,0,158000,10400.0,9000,0.0,Group 2,2017-07
6,2017-07-03,201707039018928,della,Della Suryo,Suryo,Service/ Mokado,Pulsa Indosat REG 50.000,90000,48100,41900,2900.0,0,0.0,Group 2,2017-07
7,2017-07-07,201707079291011,Sri,Sri Oki,Oki,Service/ Mokado,Pulsa Indosat REG 50.000,180000,96200,83800,5800.0,0,0.0,Group 2,2017-07
8,2017-07-03,201706218386960,Irene,Irene Hana,Hana,Service/ Mokado,[BUKBER HEMAT] Es Teler 77 : Es Teler,300000,156400,152600,10000.0,9000,0.0,Group 2,2017-07
9,2017-07-24,201707230047939,tofani,Tofani Valentina,Valentina,Fashion,Sandal Pria Sandal Gunung New Era CSA | 4 Model,675000,351900,333100,22500.0,10000,0.0,Group 1,2017-07

In [ ]:
df_pivot = df_p.pivot_table(index='month', columns='group', values='GMV', aggfunc='sum')
df_pivot.head(10)

group      Group 1    Group 2
month
2017-07  147724300  230414100
2017-08   94599100  348790700
2017-09  263786400  191482700
2017-10  114883100  150263700
2017-11  263329200  326532200
2017-12  131366800  451421300

## nomor 4

In [ ]:
df_merge = pd.merge(df_p, df_s, on='Order Number', how='left')
data_agustus = df_merge[df_merge['Paid Date'].dt.to_period('M') == '2017-08']
top_seller = data_agustus.groupby('Seller')['GMV'].sum().sort_values(ascending=False)
print(top_seller.head(10))

Seller
MOBILEPULSA APP    127241500
XLmystore           61367200
Mullia Cell         43216100
E-Bold              40180400
Voucher Plus        14056400
KeeKy               13275200
Opa Store            9470000
cemilan4u            6894500
PDAJAKARTA           6849000
AMG Gadget           6656300
Name: GMV, dtype: int64

## nomor 5

In [ ]:
fashion_september = df_merge[(df_merge['month'] == '2017-09') & (df_merge['Meta Category'] == 'Fashion')]

top_seller_fashion = fashion_september.groupby('Seller')['GMV'].sum().sort_values(ascending=False)
print(top_seller_fashion.head(10))

Seller
Distro Bandung .Inc    21301100
tokoaqila              18635800
Fadfa Collections      16569000
Bajukitaindonesia      16166900
Ets                     5630100
Dafashion butik         5573000
Faith                   4769400
Astro Maya              3518300
Bag Thinker             2795000
CV Langit Biru          2388500
Name: GMV, dtype: int64